config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  get "get_started", to: "application#get_started", as: "get_started"
  get "english_teachers", to: "application#english_teachers", as: "english_teachers"
  get "french_teachers", to: "application#french_teachers", as: "french_teachers"
  get "recruiters", to: "application#recruiters", as: "recruiters"
  get "materials", to: "application#materials", as: "materials"
  get "visas", to: "application#visas", as: "visas"
  get "hire_a_professional", to: "application#hire_a_professional", as: "hire_a_professional"
  
  get "/admin", to: "admin#dashboard", as: "admin"
  get "/admin/french", to: "admin#french_teachers", as: "admin_french_teachers"
  get "/admin/english", to: "admin#english_teachers", as: "admin_english_teachers"
  get "/admin/recruiters", to: "admin#recruiters", as: "admin_recruiters"
  get "/admin/materials", to: "admin#materials", as: "admin_materials"

  get "/admin/user/new", to: "admin#new_user", as: "admin_new_user"
  post "/admin/user/save", to: "admin#save_user", as: "admin_save_user"
  get "/admin/user/:id", to: "admin#edit_user", as: "admin_edit_user"
  post "/admin/user/:id", to: "admin#update_user", as: "admin_update_user"
  delete "/admin/user/:id", to: "admin#delete_user", as: "admin_delete_user"

  get "/admin/material/new", to: "admin#new_material", as: "admin_new_material"
  post "/admin/material/save", to: "admin#save_material", as: "admin_save_material"
  get "/admin/material/:id", to: "admin#edit_material", as: "admin_edit_material"
  post "/admin/material/:id", to: "admin#update_material", as: "admin_update_material"
  delete "/admin/material/:id", to: "admin#delete_material", as: "admin_delete_material"

  get "test", to: "application#test"
  get "download", to: "application#download_mobile_app", as: "download_mobile_app"

  root "application#index"
end

app/views/admin/dashboard.html.erb
<div class="d-flex justify-content-between mx-2">
  <%= link_to "New Client", admin_new_user_path, class: "btn btn-primary my-auto mx-2" %>

  <%= search_form_for(@q, url: "/admin", method: :get) do |f| %>
    <div class="d-flex my-auto">
      <%= f.search_field :name_cont, placeholder: "Search...", class:"form-control input-field" %>
      <%= f.submit "Search", class:"btn btn-primary mx-2" %>
    </div>
  <% end %>
</div>
<div class="container-fluid custom-container m-2 p-4">
  <table class="table table-striped">
    <thead class="thead-dark bg-custom-red">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="max-w-150">
            <div class="d-flex">
              <div class="mx-2 my-auto">
                <% if user.image.attached? %>
                  <%= image_tag user.image, class:"admin-img" %>
                <% else %>
                  <%= image_tag "default_profile", class:"admin-img" %>
                <% end %>
              </div>
              <div class="my-auto">
                <%= user.name %><br>
              </div>
            </div>
          </td>
          <td>
            <%= user.email %>
          </td>
          <td class="max-w-150">
            <%= user.phone %>
          </td>
          <td class="max-w-200">
            <div class="d-flex my-2">
              <%= link_to "edit", admin_edit_user_path(id: user.id), class: "btn btn-warning mx-2" %>
              <%= button_to "delete", admin_delete_user_path(id: user.id), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-danger mx-2" %>
            <div>
          </td>
        <tr>
      <% end %>
      <tr>
        <td colspan="4"><%= will_paginate @users %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/edit_material.html.erb
<div class="d-flex justify-content-between">
  <h1>Edit Material</h1>
  <%= link_to "Back", :back, class:"btn btn-secondary my-auto" %>
</div>
<div class="container-fluid custom-container m-2 p-4">
    <div class="m-3">
        <%= form_with(model: @material, url: admin_update_material_path(id: @material.id), method: :post) do |form| %>
            <div class="my-3">
                <%= form.label :name %>
                <%= form.text_field :name, class:"form-control input-field" %>
            </div>
            <div class="my-3">
                <%= form.label :price %>
                <%= form.number_field :price, class:"form-control input-field" %>
            </div>
            <div class="my-3">
                <%= form.label :link %>
                <%= form.text_field :link, class:"form-control input-field" %>
            </div>
            <div class="mb-3">
                <%= form.file_field :image, class:"form-control input-field" %>
            </div>

            <div class="my-3">
                <%= form.submit class: "btn btn-danger" %>
            </div>
        <% end %>
    </div>

</div>

app/views/admin/edit_user.html.erb
<div class="d-flex justify-content-between">
  <h1>Edit User</h1>
  <%= link_to "Back", :back, class:"btn btn-secondary my-auto" %>
</div>
<div class="container-fluid custom-container m-2 p-4">
    <div class="m-3">
        <%= form_with(model: @user, url: admin_update_user_path(id: @user.id), method: :post) do |form| %>
            <div class="my-3">
                <%= form.label :name %>
                <%= form.text_field :name, class:"form-control input-field" %>
            </div>
            <div class="my-3">
                <%= form.label :email %>
                <%= form.email_field :email, class:"form-control input-field" %>
            </div>
            <div class="my-3">
                <%= form.label :phone %>
                <%= form.text_field :phone, class:"form-control input-field" %>
            </div>
            <div class="mb-3">
                <%= form.file_field :image, class:"form-control input-field" %>
            </div>
            <div class="my-3">
                <%= form.label :role %>
                <%= form.select :role, options_for_select([['regular user','0'],['admin','1'],['english teacher','2'],['french teacher','3'],['recruiter','4']]), {}, { :class => 'form-control input-field' } %>
            </div>
            <div class="my-3">
                <%= form.label :rate %>
                <%= form.number_field :rate, class:"form-control input-field" %>
            </div>
            <div class="my-3">
                <%= form.label :description %>
                <%= form.text_field :description, class:"form-control input-field" %>
            </div>

            <div class="my-3">
                <%= form.submit class: "btn btn-danger" %>
            </div>
        <% end %>
    </div>

</div>

app/views/admin/english_teachers.html.erb
<div class="d-flex justify-content-between mx-2">
  <%= link_to "New English Teacher", admin_new_user_path, class: "btn btn-primary my-auto mx-2" %>

  <%= search_form_for(@q, url: "/admin/english", method: :get) do |f| %>
    <div class="d-flex my-auto">
      <%= f.search_field :name_cont, placeholder: "Search...", class:"form-control input-field" %>
      <%= f.submit "Search", class:"btn btn-primary mx-2" %>
    </div>
  <% end %>
</div>
<div class="container-fluid custom-container m-2 p-4">
  <table class="table table-striped">
    <thead class="thead-dark bg-custom-red">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Description</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="max-w-150">
            <div class="d-flex">
              <div class="mx-2 my-auto">
                <% if user.image.attached? %>
                  <%= image_tag user.image, class:"admin-img" %>
                <% else %>
                  <%= image_tag "default_profile", class:"admin-img" %>
                <% end %>
              </div>
              <div>
                <%= user.name %><br>
                <%= user.email %>
              </div>
            </div>
          </td>
          <td>
            <%= user.rate %>
          </td>
          <td class="max-w-150">
            <%= user.description %>
          </td>
          <td class="max-w-200">
            <div class="d-flex my-2">
              <%= link_to "edit", admin_edit_user_path(id: user.id), class: "btn btn-warning mx-2" %>
              <%= button_to "delete", admin_delete_user_path(id: user.id), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-danger mx-2" %>
            <div>
          </td>
        <tr>
      <% end %>
      <tr>
        <td colspan="4"><%= will_paginate @users %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/french_teachers.html.erb
<div class="d-flex justify-content-between mx-2">
  <%= link_to "New French Teacher", admin_new_user_path, class: "btn btn-primary my-auto mx-2" %>

  <%= search_form_for(@q, url: "/admin/french", method: :get) do |f| %>
    <div class="d-flex my-auto">
      <%= f.search_field :name_cont, placeholder: "Search...", class:"form-control input-field" %>
      <%= f.submit "Search", class:"btn btn-primary mx-2" %>
    </div>
  <% end %>
</div>
<div class="container-fluid custom-container m-2 p-4">
  <table class="table table-striped">
    <thead class="thead-dark bg-custom-red">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Description</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="max-w-150">
            <div class="d-flex">
              <div class="mx-2 my-auto">
                <% if user.image.attached? %>
                  <%= image_tag user.image, class:"admin-img" %>
                <% else %>
                  <%= image_tag "default_profile", class:"admin-img" %>
                <% end %>
              </div>
              <div>
                <%= user.name %><br>
                <%= user.email %>
              </div>
            </div>
          </td>
          <td>
            <%= user.rate %>
          </td>
          <td class="max-w-150">
            <%= user.description %>
          </td>
          <td class="max-w-200">
            <div class="d-flex my-2">
              <%= link_to "edit", admin_edit_user_path(id: user.id), class: "btn btn-warning mx-2" %>
              <%= button_to "delete", admin_delete_user_path(id: user.id), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-danger mx-2" %>
            <div>
          </td>
        <tr>
      <% end %>
      <tr>
        <td colspan="4"><%= will_paginate @users %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/materials.html.erb
<div class="d-flex justify-content-between mx-2">
  <%= link_to "New Material", admin_new_material_path, class: "btn btn-primary my-auto mx-2" %>

  <%= search_form_for(@q, url: "/admin/materials", method: :get) do |f| %>
    <div class="d-flex my-auto">
      <%= f.search_field :name_cont, placeholder: "Search...", class:"form-control input-field" %>
      <%= f.submit "Search", class:"btn btn-primary mx-2" %>
    </div>
  <% end %>
</div>
<div class="container-fluid custom-container m-2 p-4">
  <table class="table table-striped">
    <thead class="thead-dark bg-custom-red">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">link</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @materials.each do |material| %>
        <tr>
          <td class="max-w-150">
            <div class="d-flex">
              <div class="mx-2 my-auto">
                <% if material.image.attached? %>
                  <%= image_tag material.image, class:"admin-img" %>
                <% else %>
                  <%= image_tag "default_profile", class:"admin-img" %>
                <% end %>
              </div>
              <div>
                <%= material.name %>
              </div>
            </div>
          </td>
          <td>
            <%= material.price %>
          </td>
          <td class="max-w-150">
            <%= material.link %>
          </td>
          <td class="max-w-200">
            <div class="d-flex my-2">
              <%= link_to "edit", admin_edit_material_path(id: material.id), class: "btn btn-warning mx-2" %>
              <%= button_to "delete", admin_delete_material_path(id: material.id), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-danger mx-2" %>
            <div>
          </td>
        <tr>
      <% end %>
      <tr>
        <td colspan="4"><%= will_paginate @materials %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/new_material.html.erb
<div class="d-flex justify-content-between">
  <h1>New Material</h1>
  <%= link_to "Back", :back, class:"btn btn-secondary my-auto" %>
</div>
<div class="container-fluid custom-container m-2 p-4">
    <div class="m-3">
        <%= form_with(model: @material, url: admin_save_material_path, method: :post) do |form| %>
            <div class="my-3">
                <%= form.label :name %>
                <%= form.text_field :name, class:"form-control input-field" %>
            </div>
            
            <div class="my-3">
                <%= form.label :price %>
                <%= form.number_field :price, class:"form-control input-field" %>
            </div>
            <div class="my-3">
                <%= form.label :link %>
                <%= form.text_field :link, class:"form-control input-field" %>
            </div>
            <div class="mb-3">
                <%= form.file_field :image, class:"form-control input-field" %>
            </div>
            
            <div class="my-3">
                <%= form.submit class: "btn btn-danger" %>
            </div>
        <% end %>
    </div>
</div>

app/views/admin/new_user.html.erb
<div class="d-flex justify-content-between">
  <h1>New User</h1>
  <%= link_to "Back", :back, class:"btn btn-secondary my-auto" %>
</div>
<div class="container-fluid custom-container m-2 p-4">
    <div class="m-3">
        <%= form_with(model: @user, url: admin_save_user_path, method: :post) do |form| %>
            <div class="my-3">
                <%= form.label :name %>
                <%= form.text_field :name, class:"form-control input-field" %>
            </div>
            <div class="my-3">
                <%= form.label :email %>
                <%= form.email_field :email, class:"form-control input-field" %>
            </div>
            <div class="my-3">
                <%= form.label :phone %>
                <%= form.text_field :phone, class:"form-control input-field" %>
            </div>
            <div class="mb-3">
                <%= form.file_field :image, class:"form-control input-field" %>
            </div>
            <div class="my-3">
                <%= form.label :password %>
                <%= form.password_field :password, class:"form-control input-field" %>
            </div>
            <div class="my-3">
                <%= form.label :password_confirmation %>
                <%= form.password_field :password_confirmation, class:"form-control input-field" %>
            </div>
            <div class="my-3">
                <%= form.label :role %>
                <%= form.select :role, options_for_select([['regular user','0'],['admin','1'],['english teacher','2'],['french teacher','3'],['recruiter','4']]), {}, { :class => 'form-control input-field' } %>
            </div>  
            <div class="my-3">
                <%= form.label :rate %>
                <%= form.number_field :rate, class:"form-control input-field" %>
            </div>
            <div class="my-3">
                <%= form.label :description %>
                <%= form.text_field :description, class:"form-control input-field" %>
            </div>

            <div class="my-3">
                <%= form.submit class: "btn btn-danger" %>
            </div>
        <% end %>
    </div>
</div>

app/views/admin/recruiters.html.erb
<div class="d-flex justify-content-between mx-2">
  <%= link_to "New Recruiter", admin_new_user_path, class: "btn btn-primary my-auto mx-2" %>

  <%= search_form_for(@q, url: "/admin/recruiters", method: :get) do |f| %>
    <div class="d-flex my-auto">
      <%= f.search_field :name_cont, placeholder: "Search...", class:"form-control input-field" %>
      <%= f.submit "Search", class:"btn btn-primary mx-2" %>
    </div>
  <% end %>
</div>
<div class="container-fluid custom-container m-2 p-4">
  <table class="table table-striped">
    <thead class="thead-dark bg-custom-red">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Description</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="max-w-150">
            <div class="d-flex">
              <div class="mx-2 my-auto">
                <% if user.image.attached? %>
                  <%= image_tag user.image, class:"admin-img" %>
                <% else %>
                  <%= image_tag "default_profile", class:"admin-img" %>
                <% end %>
              </div>
              <div>
                <%= user.name %><br>
                <%= user.email %>
              </div>
            </div>
          </td>
          <td>
            <%= user.rate %>
          </td>
          <td class="max-w-150">
            <%= user.description %>
          </td>
          <td class="max-w-200">
            <div class="d-flex my-2">
              <%= link_to "edit", admin_edit_user_path(id: user.id), class: "btn btn-warning mx-2" %>
              <%= button_to "delete", admin_delete_user_path(id: user.id), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-danger mx-2" %>
            <div>
          </td>
        <tr>
      <% end %>
      <tr>
        <td colspan="4"><%= will_paginate @users %></td>
      </tr>
    </tbody>
  </table>
</div>