config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  get "get_started", to: "application#get_started", as: "get_started"
  get "english_teachers", to: "application#english_teachers", as: "english_teachers"
  get "french_teachers", to: "application#french_teachers", as: "french_teachers"
  get "recruiters", to: "application#recruiters", as: "recruiters"
  get "materials", to: "application#materials", as: "materials"
  get "visas", to: "application#visas", as: "visas"
  get "hire_a_professional", to: "application#hire_a_professional", as: "hire_a_professional"
  
  get "/admin", to: "admin#dashboard", as: "admin"
  get "/admin/french", to: "admin#french_teachers", as: "admin_french_teachers"
  get "/admin/english", to: "admin#english_teachers", as: "admin_english_teachers"
  get "/admin/recruiters", to: "admin#recruiters", as: "admin_recruiters"
  get "/admin/materials", to: "admin#materials", as: "admin_materials"

  get "/admin/user/new", to: "admin#new_user", as: "admin_new_user"
  post "/admin/user/save", to: "admin#save_user", as: "admin_save_user"
  get "/admin/user/:id", to: "admin#edit_user", as: "admin_edit_user"
  post "/admin/user/:id", to: "admin#update_user", as: "admin_update_user"
  delete "/admin/user/:id", to: "admin#delete_user", as: "admin_delete_user"

  get "/admin/material/new", to: "admin#new_material", as: "admin_new_material"
  post "/admin/material/save", to: "admin#save_material", as: "admin_save_material"
  get "/admin/material/:id", to: "admin#edit_material", as: "admin_edit_material"
  post "/admin/material/:id", to: "admin#update_material", as: "admin_update_material"
  delete "/admin/material/:id", to: "admin#delete_material", as: "admin_delete_material"

  get "test", to: "application#test"
  get "download", to: "application#download_mobile_app", as: "download_mobile_app"

  root "application#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
    end

    def get_started
    end

    def english_teachers
        @q = User.where(role: 2).ransack(params[:q])
        @users = @q.result(distinct: true).paginate(page: params[:page], per_page: 10)
    end

    def french_teachers
        @q = User.where(role: 3).ransack(params[:q])
        @users = @q.result(distinct: true).paginate(page: params[:page], per_page: 10)
    end

    def recruiters
        @q = User.where(role: 4).ransack(params[:q])
        @users = @q.result(distinct: true).paginate(page: params[:page], per_page: 10)
    end
    
    def materials
        @q = Material.ransack(params[:q])
        @materials = @q.result(distinct: true).paginate(page: params[:page], per_page: 10)
    end

    def visas        
    end

    def hire_a_professional
    end

    def download_mobile_app
        send_file "#{Rails.root}/app/assets/mobile/app.apk", x_sendfile: true 
    end

    def test
        render layout: "layouts/admin"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/english_teachers.html.erb
<div class="container-fluid m-0 p-0 p-2">
    <div class="m-3 m-md-5">
        <div class="d-md-flex justify-content-between my-3">
            <%= link_to "Book a Teacher", "https://docs.google.com/forms/d/e/1FAIpQLSevvPvgH9mqJu8PQaRrdU8l36WQn1mP-7VfYhGUV3q6rBcHLA/viewform?usp=send_form", class:"btn btn-danger my-3 my-md-auto mx-1 mx-md-2", target: "_blank" %>
            <%= search_form_for(@q, url: "/english_teachers", method: :get) do |f| %>
                <div class="d-flex my-auto">
                <%= f.search_field :name_cont, placeholder: "Search...", class:"form-control input-field" %>
                <%= f.submit "Search", class:"btn btn-danger mx-2" %>
                </div>
            <% end %>
        </div>
        <div class="row">
            <% @users.each do |user| %>
                <div class="col-md-3 my-3">
                    <div class="card shadow p-2 text-center">
                        <a href="/" class="nav-link">
                            <% if user.image.attached? %>
                                <%= image_tag user.image, class:"profile-image teacher" %>
                            <% else %>
                                <%= image_tag "default_profile", class:"profile-image teacher" %>
                            <% end %>
                            <div class="mt-3 text-custom-red">
                                <%= user.name %><br>
                                <%= user.description %>
                            </div>
                            <span class="text-success"><%= user.rate %>$/hr</span>
                        </a>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/application/french_teachers.html.erb
<div class="container-fluid m-0 p-0 p-2">
    <div class="m-3 m-md-5">
        <div class="d-md-flex justify-content-between my-3">
            <%= link_to "Book a Teacher", "https://docs.google.com/forms/d/e/1FAIpQLSevvPvgH9mqJu8PQaRrdU8l36WQn1mP-7VfYhGUV3q6rBcHLA/viewform?usp=send_form", class:"btn btn-danger my-3 my-md-auto mx-1 mx-md-2", target: "_blank" %>
            <%= search_form_for(@q, url: "/french_teachers", method: :get) do |f| %>
                <div class="d-flex my-auto">
                <%= f.search_field :name_cont, placeholder: "Search...", class:"form-control input-field" %>
                <%= f.submit "Search", class:"btn btn-danger mx-2" %>
                </div>
            <% end %>
        </div>
        <div class="row">
            <% @users.each do |user| %>
                <div class="col-md-3 my-3">
                    <div class="card shadow p-2 text-center">
                        <a href="" class="nav-link">
                            <% if user.image.attached? %>
                                <%= image_tag user.image, class:"profile-image teacher" %>
                            <% else %>
                                <%= image_tag "default_profile", class:"profile-image teacher" %>
                            <% end %>
                            <div class="mt-3 text-custom-red">
                                <%= user.name %><br>
                                <%= user.description %>
                            </div>
                            <span class="text-success"><%= user.rate %>$/hr</span>
                        </a>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/application/get_started.html.erb
<div class="container-fluid m-0 p-0 p-2">
    <div class="text-center">
        <%= link_to "Quick Advice", "https://calendly.com/matchmewithcanada/meeting", class:"btn bg-custom-pink text-white my-3", target: "_blank" %>
        <h1 class="text-custom-red text-uppercase my-3"><i>Fastest path to canada</i></h1>
    </div>
    <div class="d-flex flex-row w-100">
        <div class="banner card shadow">
            <%= image_tag "img3", class:"img-fluid w-full h-auto" %>
        </div>
    </div>
    <div class="text-center">
        <h3 class="text-custom-red my-3">Step 1: Match Me With Jobs</h2>
    </div>
    <div class="d-flex flex-row w-100">
        <div class="banner card shadow">
            <%= image_tag "img9", class:"img-fluid w-full h-auto" %>
        </div>
    </div>
    <div class="text-center banner">
        <p class="text-custom-pink my-3">
            Finding a job isn't that easy if you don't prepare very well for it. Crafting a Professional LinkedIn and CV
            is the best start. These are the first things your employer will look at. They are critical for the first 
            impression. Ifthey don't look professional and do not respect the canadian culture (sexism, genderism, racism...)
            you have a really high chance of getting rejected. That is why you have to make sure you have established 
            a professional portfolio. Match yourself with a Recruiter/HR.
        </p>
        <%= link_to "Match Me With Canadian Recruiters/HRs", recruiters_path, class:"btn btn-danger my-3" %><br>
        <%= link_to "Test Your Luck", "https://t.me/jobsmatchmewithcanada", class:"btn btn-danger my-3", target: "_blank" %><br>
        <%= link_to "Find a Job With a Consultant", hire_a_professional_path, class:"btn btn-danger my-3" %><br>    
        <h2 class="text-custom-red my-3">Step 2: Match Me With English and French</h2>
    </div>
    <div class="d-flex flex-row w-100">
        <div class="banner card shadow">
            <%= image_tag "img12", class:"img-fluid w-full h-auto" %>
        </div>
    </div>
    <div class="text-center banner">
        <%= link_to "Book and Materials", materials_path, class:"btn btn-danger my-3" %><br> 
        <p class="text-custom-pink my-3">
            Also, you have to consider learning some languages, however, it is not mandatory, but for sure it 
            will boost your chances in finding a job. After all, you will have to communicate in French or 
            English at work. But, to be able to immigrate or apply for a Permanent Residency, even if you have
            a work permit, you must pass language exams both in English and in French. Please take a look.
        </p>
        <%= link_to "Match Me With English Teachers", english_teachers_path, class:"btn btn-danger my-3" %><br>
        <p class="text-custom-pink my-3">
            The french language is extremely demanded to integrate more french speakers across Canada since 
            only in Quebec people speak french. Canada wants to popularize its official language across its 
            lands. Learn french you will never regret it!
        </p>
        <%= link_to "Match Me With French Teachers", french_teachers_path, class:"btn btn-danger my-3" %><br>    
        <h2 class="text-custom-red my-3">Step 3: Match Me With Canadian Education</h2>
    </div>
    <div class="d-flex flex-row w-100">
        <div class="banner card shadow">
            <%= image_tag "wes.jpeg", class:"img-fluid w-full h-auto" %>
        </div>
    </div>
    <div class="text-center">
        <%= link_to "Education Credential Assessment", "https://www.wes.org", target: "_blank", class:"btn btn-danger my-3" %><br>
        <h2 class="text-custom-red my-3">Step 4: Match Me With Visa</h2>
    </div>
    <div class="d-flex flex-row w-100">
        <div class="banner card shadow">
            <%= image_tag "img7", class:"img-fluid w-full h-auto" %>
        </div>
    </div>
    <div class="text-center">
        <%= link_to "Visas", visas_path, class:"btn btn-danger my-3" %><br>
    </div>
</div>

app/views/application/hire_a_professional.html.erb
<div class="container-fluid m-0 p-0 p-2">
    <div class="text-center">
        <div class="text-custom-red text-center banner my-3">
            <p>If you are certain that you are fully prepared for finding a job then all you have to do is to 
            hire a professional to do the job. Searching online on all the platforms will not help because Canada 
            strongly protects its labour, and companies will not be able to hire someone from abroad unless it 
            hires a consultant to prepare its papers. It has to pass certain assesments and provide proof that 
            the position it is seeking isn't available in Canada. That is why hiring a consultant to do the job 
            for you will enormously increase your chances and will secure a 100% guaranteed job.</p>
        </div>
    </div>
    <div class="d-flex flex-row w-100">
        <div class="banner card shadow">
            <%= image_tag "img14", class:"img-fluid w-full h-auto" %>
        </div>
    </div>
    <div class="text-center">
        <div class="text-custom-red text-center banner my-3">
            <p>Finding a job for you may require some time ranging from one to ten months. The consultant will have to take your portfolio and contact or explore locations in order to match you with the best company. This requires a lot of work, and a lot of contributions. This is why hiring him/her requirs someone who is serious, determined, patient, and persistent to find a job. Thus, the consultant will need a 300$ retainer as a proof of this person's commitment.</p>
        </div>
    </div>
    <div class="d-flex flex-row w-100">
        <div class="banner card shadow">
            <%= image_tag "img13", class:"img-fluid w-full h-auto" %>
        </div>
    </div>
    <div class="text-center">
        <div class="text-custom-red text-center banner my-3">
            <p>After the consultant matches you with a company, the next step will be 100% guaranteed. You will have the visa in one to two months. And you will land in Canada. Good Luck! Wish you all the best.</p>
        </div>
        <%= link_to "Proceed", "https://docs.google.com/forms/d/e/1FAIpQLSdGWmVcLJtBGw6LgPtpFRLMcJBbqaLOar8ZP5KLrway_vwGYA/viewform?usp=send_form", class:"btn btn-danger my-3", target: "_blank" %><br>
        <div class="text-custom-gray text-center banner my-3">
            <p>Note: Click proceed to fill the form and book a meeting with the consultant. Make sure you have read the informations before booking.</p>
        </div>
    </div>
</div>
        

app/views/application/index.html.erb
<!--<script src="http://code.jquery.com/jquery-2.2.1.min.js"></script>

<div class="preloader">
    <%= image_tag "logo", class:"small-pic" %>
</div>

<script>
    $(document).ready(function(){
    setTimeout(function () {
		$('.preloader').fadeOut();
	}, 2000);
    });
</script>-->

<div class="container-fluid m-0 p-0 p-2">
    <div class="text-center">
        <%= link_to "Download Mobile App", download_mobile_app_path, class:"btn btn-danger my-3" %>
    </div>
    <div class="d-flex flex-row w-100">
        <div class="banner card shadow">
            <%= image_tag "img1", class:"img-fluid w-full h-auto" %>
        </div>
    </div>
    <div>
        <h2 class="text-custom-red text-center my-4"><i>Your first step towards Canada</i></h2>
    </div>
    <div class="d-flex flex-row w-100">
        <div class="banner card shadow">
            <%= image_tag "img2", class:"img-fluid w-full h-auto" %>
        </div>
    </div>
    <div class="text-center">
        <%= link_to "Get Started", get_started_path, class:"btn btn-danger my-3" %>
    </div>
    <div class="text-custom-pink text-center banner">
        <blockquote>
            <q>10-year dreams. 5-minute actions. Where do i want to be in 10 years? What can i do in the next 5 minutes to contribute to that outcome?</q><br>
            -James Clear
        </blockquote><br>

        <blockquote>
            <q>Action is hope. At the end of each day. when you've done your work, you lie there and think, Well, i'll be dammed, I did this today. It doesn't matter how good it is, or how bad -- you did it. At the end of the week you'll have a certain amount of accumulation. At the end of the year, you look back and say, I'll be damned, it's been a good year.</q><br>
            -Ray Bradbury
        </blockquote><br>

        <blockquote>
            <q>When someone tells me "no", it doesn't mean i can't do it, it simply means i can't do it with them.</q><br>
            -Karen E. Quinones
        </blockquote><br>

        <blockquote>
            <q>Even if you're on the right track, you'll still get run over if you just sit there.</q><br>
            -Will Rogers
        </blockquote><br>

        <blockquote>
            <q>Real difficulties can be overcome; it is only the imaginary ones that are unconquerable</q><br>
            -Theodore N. Veil
        </blockquote><br>

        <blockquote>
            <q>You'll feel better once you get started.</q><br>
            -James Clear
        </blockquote><br>
    </div>
</div>

app/views/application/materials.html.erb
<div class="container-fluid m-0 p-0 p-2">
    <div class="m-3 m-md-5">
        <div class="d-flex justify-content-end my-3">
            <%= search_form_for(@q, url: "/materials", method: :get) do |f| %>
                <div class="d-flex my-auto">
                    <%= f.search_field :name_cont, placeholder: "Search...", class:"form-control input-field" %>
                    <%= f.submit "Search", class:"btn btn-danger mx-2" %>
                </div>
            <% end %>
        </div>
        <div class="row">
            <% @materials.each do |material| %>
                <div class="col-md-3 my-3">
                    <div class="card shadow p-2 text-center">
                        <a href="<%= material.link %>" class="nav-link" target="__blank">
                            <% if material.image.attached? %>
                                <%= image_tag material.image, class:"profile-image book" %>
                            <% else %>
                                <%= image_tag "default_profile", class:"profile-image book" %>
                            <% end %>
                            <div class="mt-3 text-custom-red">
                                <%= material.name %>
                            </div>
                            <span class="text-success"><%= material.price %>$</span>
                        </a>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/application/recruiters.html.erb
<div class="container-fluid m-0 p-0 p-2">
    <div class="m-3 m-md-5">
        <div class="d-md-flex justify-content-between my-2">
            <%= link_to "Book a Recruiter", "https://calendly.com/matchmewithcanada/meeting", class:"btn btn-danger my-3 my-md-auto mx-1 mx-md-2", target:"_blank" %>
            <%= search_form_for(@q, url: "/recruiters", method: :get) do |f| %>
                <div class="d-flex my-auto">
                <%= f.search_field :name_cont, placeholder: "Search...", class:"form-control input-field" %>
                <%= f.submit "Search", class:"btn btn-danger mx-2" %>
                </div>
            <% end %>
        </div>
        <div class="row">
            <% @users.each do |user| %>
                <div class="col-md-3 my-3">
                    <div class="card shadow p-2 text-center">
                        <a href="/" class="nav-link">
                            <% if user.image.attached? %>
                                <%= image_tag user.image, class:"profile-image teacher" %>
                            <% else %>
                                <%= image_tag "default_profile", class:"profile-image teacher" %>
                            <% end %>
                            <div class="mt-3 text-custom-red">
                                <%= user.name %><br>
                                <%= user.description %>
                            </div>
                            <span class="text-success"> <%= user.rate %>$/package</span>
                        </a>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/application/test.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/application/visas.html.erb
<div class="container-fluid m-0 p-0 p-2">
    <div class="text-center">
        <%= link_to "Quick Advice", "https://calendly.com/matchmewithcanada/meeting", class:"btn bg-custom-pink text-white my-3" %>
    </div>
    <div class="d-flex flex-row w-100">
        <div class="banner card shadow">
            <%= image_tag "img8", class:"img-fluid w-full h-auto" %>
        </div>
    </div>
    <div class="text-center">
        <%= link_to "Hire a Pro to Find you a Job", hire_a_professional_path, class:"btn btn-danger my-3" %><br>
    </div>
    <div class="d-flex flex-row w-100">
        <div class="banner card shadow">
            <%= image_tag "img18", class:"img-fluid w-full h-auto" %>
        </div>
    </div>
    <div class="text-center">
        <%= link_to "Immigrate", "https://docs.google.com/forms/d/e/1FAIpQLSdvP7ngSnU1pW_HsTsyLSovjVCZFGOI0atv0VZ4QTcwyr7uVQ/viewform?usp=send_form", class:"btn btn-danger my-3" %><br>
        <div class="text-custom-pink text-center banner">
            <p>Before immigrating you have to</p>
        </div>
        <%= link_to "Do the IELTS Exam", english_teachers_path, class:"btn bg-custom-pink text-white my-3" %><br>
        <%= link_to "Do the TCF/TEF Exam", french_teachers_path, class:"btn bg-custom-pink text-white my-3" %><br>
        <%= link_to "Education Credential Assesment", "https://wes.org", class:"btn bg-custom-pink text-white my-3", target: "_blank" %><br>
        <%= link_to "Canadian Reference Letter", recruiters_path, class:"btn bg-custom-pink text-white my-3" %><br>
    </div>
    <div class="d-flex flex-row w-100">
        <div class="banner card shadow">
            <%= image_tag "img4", class:"img-fluid w-full h-auto" %>
        </div>
    </div>
    <div class="text-center">
        <%= link_to "Find a learning institute", "https://docs.google.com/forms/d/e/1FAIpQLSf7hFuK27o6IG79XB4w4wA6AZak_vBk9l8GZ5tpeN4dmx-0mA/viewform?usp=send_form", class:"btn btn-danger my-3", target: "_blank" %><br>
        <div class="text-custom-pink text-center banner">
            <p>Most of the learning institutes require:</p>
        </div>
        <%= link_to "English Test", english_teachers_path, class:"btn bg-custom-pink text-white my-3" %><br>
        <%= link_to "French Test", french_teachers_path, class:"btn bg-custom-pink text-white my-3" %><br>
    </div> 
    <div class="d-flex flex-row w-100">
        <div class="banner card shadow">
            <%= image_tag "img19", class:"img-fluid w-full h-auto" %>
        </div>
    </div>
    <div class="text-center">
        <%= link_to "I have a job offer", "https://docs.google.com/forms/d/e/1FAIpQLSeuZG2-NIu3CS6DOPSZTXW47bSRmrX9c23-UZDVKwS5G6s_Ng/viewform?usp=send_form", class:"btn btn-danger my-3", target: "_blank" %><br>
    </div> 
    <div class="d-flex flex-row w-100">
        <div class="banner card shadow">
            <%= image_tag "img5", class:"img-fluid w-full h-auto" %>
        </div>
    </div>
    <div class="text-center">
        <%= link_to "I have a letter of acceptance", "https://docs.google.com/forms/d/e/1FAIpQLSek1XAmZU9AcFaNuubK6ZB1_nxvWA3J-mw9NbEcVfT4ttOW5w/viewform", class:"btn btn-danger my-3", target: "_blank" %><br>
    </div> 
    <div class="d-flex flex-row w-100">
        <div class="banner card shadow">
            <%= image_tag "img6", class:"img-fluid w-full h-auto" %>
        </div>
    </div>
    <div class="text-center">
        <%= link_to "Guidance / Problem Solving 300$/hr", "https://docs.google.com/forms/d/e/1FAIpQLScGx_C58UbUU3m3p1EuSZoWOTbBzumCnNFVpzfkmhNeBEJn0g/viewform", class:"btn btn-danger my-3", target: "_blank" %><br>
    </div> 
</div>