config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  get "get_started", to: "application#get_started", as: "get_started"
  get "english_teachers", to: "application#english_teachers", as: "english_teachers"
  get "french_teachers", to: "application#french_teachers", as: "french_teachers"
  get "recruiters", to: "application#recruiters", as: "recruiters"
  get "materials", to: "application#materials", as: "materials"
  get "visas", to: "application#visas", as: "visas"
  get "hire_a_professional", to: "application#hire_a_professional", as: "hire_a_professional"
  
  get "/admin", to: "admin#dashboard", as: "admin"
  get "/admin/french", to: "admin#french_teachers", as: "admin_french_teachers"
  get "/admin/english", to: "admin#english_teachers", as: "admin_english_teachers"
  get "/admin/recruiters", to: "admin#recruiters", as: "admin_recruiters"
  get "/admin/materials", to: "admin#materials", as: "admin_materials"

  get "/admin/user/new", to: "admin#new_user", as: "admin_new_user"
  post "/admin/user/save", to: "admin#save_user", as: "admin_save_user"
  get "/admin/user/:id", to: "admin#edit_user", as: "admin_edit_user"
  post "/admin/user/:id", to: "admin#update_user", as: "admin_update_user"
  delete "/admin/user/:id", to: "admin#delete_user", as: "admin_delete_user"

  get "/admin/material/new", to: "admin#new_material", as: "admin_new_material"
  post "/admin/material/save", to: "admin#save_material", as: "admin_save_material"
  get "/admin/material/:id", to: "admin#edit_material", as: "admin_edit_material"
  post "/admin/material/:id", to: "admin#update_material", as: "admin_update_material"
  delete "/admin/material/:id", to: "admin#delete_material", as: "admin_delete_material"

  get "test", to: "application#test"
  get "download", to: "application#download_mobile_app", as: "download_mobile_app"

  root "application#index"
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-primary m-3">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:danger] %>
    <div class="alert alert-danger m-3">
        <%= flash[:danger] %>
    </div>
<% end %>

<% if flash[:warning] %>
    <div class="alert alert-warning m-3">
        <%= flash[:warning] %>
    </div>
<% end %>

<% if flash[:success] %>
    <div class="alert alert-success m-3">
        <%= flash[:success] %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <div class="text-center my-3 mx-2">
        All Rights Reserved 2023 <br>
        <span class="text-custom-red">Match Me With Canada<span>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-light d-flex justify-content-between">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to "Match Me With Canada", root_path, class:"navbar-brand mx-3" %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto"> 
                <li class="nav-item">
                    <%= link_to "Contact us", "https://t.me/Soloman_A_Antoun", class:"nav-link", target: "_blank" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Help", "https://calendly.com/matchmewithcanada/meeting", class:"nav-link", target: "_blank" %>
                </li>
                <li class="nav-item">
                    <%= link_to "News and Updates", "https://t.me/matchmewithcanadanews", class:"nav-link", target: "_blank" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Download Mobile App", download_mobile_app_path, class:"nav-link" %>
                </li>
            </ul>
        </div>
        <div class="d-flex" id="communications">
            <div class="mx-2 mx-md-3">
                <a href="mailto:matchmewithcanada@gmail.com" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                        <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z"/>
                    </svg>
                </a>
            </div>
            <div class="mx-2 mx-md-3">
                <a href="https://calendly.com/matchmewithcanada/meeting" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
                    </svg>
                </a>
            </div>
        </div>
    </nav>
</header>
<br><br>

app/views/layouts/_sidenav.html.erb
<div class="col-auto col-md-3 col-xl-2 px-0 bg-custom-red">
    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100 w-100">
        <a href="/admin" class="w-100 my-2 text-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            MatchMeWithCanada
        </a>
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center w-100" id="menu">
            <li>
                <%= link_to "Clients", admin_path, class:"nav-link px-0 text-white" %>
            </li>
            <li>
                <%= link_to "English Teachers", admin_english_teachers_path, class:"nav-link px-0 text-white" %>
            </li>
            <li>
                <%= link_to "French Teachers", admin_french_teachers_path, class:"nav-link px-0 text-white" %>
            </li>
            <li>
                <%= link_to "Recruiters", admin_recruiters_path, class:"nav-link px-0 text-white" %>
            </li>
            <li>
                <%= link_to "Materials", admin_materials_path, class:"nav-link px-0 text-white" %>
            </li>
            <li>
                <%= button_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link px-0 text-white"  %>
            </li>
        </ul>
    </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatchMeWithCanada | Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('logo') %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <%= render "layouts/sidenav" %>
            <div class="col py-3">
                <%= render "layouts/flash" %>
                <%= yield %>
            </div>
        </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatchMeWithCanada</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('logo') %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>